server:
  port: 8089
spring:
  h2:
    console:
      enabled: true
      settings:
          web-allow-others: true
  application:
    name: PizzaCooker
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:pizza-cooker;DB_CLOSE_DELAY=0;
      username: cooker
      password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
            use_jdbc_metadata_defaults: false
        ddl-auto: update
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
logging:
  file: logs/application.log
  level:
    org.springframework.web: DEBUG
    baltic.amadeus.pizzacooker: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
cooker-machine.cook-count.limit: 20
